version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_gestionacademicautp
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: utp_gestion_academica_db_mysql
      MYSQL_USER: Franco
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15
    container_name: postgres_gestionacademicautp
    environment:
      POSTGRES_DB: utp_gestion_academica_db_pg
      POSTGRES_USER: franco
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U franco"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    container_name: mongo_gestionacademicautp
    environment:
      MONGO_INITDB_DATABASE: utp_proyectos_investigacion_db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_gestionacademicautp
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
